version: "3.6" 
services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: test
#        volumes:
#            - postgres:/var/lib/postgresql/data
#Remove these for persistent data storage.

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - "5431:80"
        depends_on: 
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: "oskar.oestby@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "test"

#volumes:
#    postgres:
